### ISSUE TITLE
Live Example of using merchant.js?

### ISSUE THREAD

**Issue by Marak** [Flaque/merchant.js#3]
Is there a live demo of merchant.js we can see?

It would probably help to include example / demo file for users to try.

**Comment by Flaque** [comment]
Working on that at the moment: https://github.com/flaque/handshakers 

(Though it should be noted, this library is still pretty untested in the real world 😅) 

Also, @Marak, just FYI: Thanks so much for making Faker. I've used in past projects and it made me really happy.

**Comment by Marak** [comment]
Would be nice to have a small minimal working example in this repo.

Thanks for the kind words.

**Comment by Flaque** [comment]
Okay, I'll see about adding a minimal example inside the project then <3

**Comment by Flaque** [comment]
Cool @Marak! Live example is up via commit: 895f75ba3d31cbbb62d4e273860a003d4e4bd63d

[Live Link here](https://merchant-example.now.sh/)

**Comment by Marak** [comment]
Super cool, thanks!

Idle games are neat. Glad to see someone working on a framework to build them.
