### ISSUE TITLE
Restore demo

### ISSUE THREAD

**Issue by Alexintosh** [Flaque/merchant.js#5]
At the moment the demo is offline.

**Comment by Flaque** [comment]
O.O Just woke up. Is it still offline? Seems good to me: https://merchant-example.now.sh/

**Comment by Alexintosh** [comment]
I can see it now, was a 404 some hours ago. Will close the issue, thanks.

**Comment by Flaque** [comment]
Cool, thanks for the heads up though! :D

**Comment by Alexintosh** [comment]
Again :( https://imgur.com/a/gOu6W

**Comment by Flaque** [comment]
Hmm :( Maybe I shouldn't use `now`?

**Comment by Flaque** [comment]
Rebooted it. But I believe there's some issue in the `start` script that's causing it to fail anytime now needs to redeploy it onto another instance or scale it or whatnot.
